using System;
using System.Collections;
using System.IO;

namespace LFC_Tema2
{
    class Program
    {
        static void Main(string[] args)
        {
            string inputFile = "input.txt";
            string tokensOutputFile = "tokens.txt";
            string globalVarsOutputFile = "global_variables.txt";
            string functionsOutputFile = "functions.txt";
            string errorsOutputFile = "errors.txt";

            
            if (args.Length > 0)
            {
                inputFile = args[0];
            }

            try
            {
                //citire fisierul de intrare
                if (!File.Exists(inputFile))
                {
                    Console.WriteLine("Error: Input file '{0}' not found.", inputFile);
                    File.WriteAllText(errorsOutputFile, "Error: Input file '" + inputFile + "' not found.\n");
                    return;
                }

                string sourceCode = File.ReadAllText(inputFile);
                Console.WriteLine("Source code loaded from: {0}", inputFile);
                Console.WriteLine("File size: {0} characters\n", sourceCode.Length);

                // analiza lexicala
                Console.WriteLine("=== PHASE 1: Lexical Analysis ===");
                MiniLangLexer lexer = new MiniLangLexer(sourceCode);
                ArrayList tokens = lexer.Tokenize();
                Console.WriteLine("Lexical analysis completed");
                Console.WriteLine("Found {0} tokens\n", tokens.Count);

                // salvare tokeni in file
                SaveTokens(tokens, tokensOutputFile);
                Console.WriteLine("Tokens saved to: {0}\n", tokensOutputFile);

                //analiza sintactica
                Console.WriteLine("=== PHASE 2: Syntactic Analysis ===");
                MiniLangParser parser = new MiniLangParser(tokens);
                ProgramNode program = parser.Parse();
                Console.WriteLine("Syntactic analysis completed");
                Console.WriteLine("Global variables: {0}", program.GlobalVariables.Count);
                Console.WriteLine("Functions: {0}\n", program.Functions.Count);

                // analiza semantica
                Console.WriteLine("=== PHASE 3: Semantic Analysis ===");
                CompilerVisitor visitor = new CompilerVisitor();
                visitor.ProcessTokens(tokens);
                visitor.Visit(program);
                
                ArrayList allErrors = new ArrayList();
                
                ArrayList lexicalErrors = lexer.GetLexicalErrors();
                for (int i = 0; i < lexicalErrors.Count; i++)
                    allErrors.Add(lexicalErrors[i]);
                
                ArrayList parserErrors = parser.GetErrors();
                for (int i = 0; i < parserErrors.Count; i++)
                    allErrors.Add(parserErrors[i]);
                
                ArrayList semanticErrors = visitor.GetErrors();
                for (int i = 0; i < semanticErrors.Count; i++)
                    allErrors.Add(semanticErrors[i]);

                if (allErrors.Count == 0)
                {
                    Console.WriteLine("Semantic analysis completed - No errors found\n");
                }
                else
                {
                    Console.WriteLine("Semantic analysis completed with {0} error(s)\n", allErrors.Count);
                }

                //salvare rezultate in fisiere
                SaveGlobalVariables(visitor.GetGlobalVariables(), globalVarsOutputFile);
                Console.WriteLine("Global variables saved to: {0}", globalVarsOutputFile);

                SaveFunctions(visitor.GetFunctions(), functionsOutputFile);
                Console.WriteLine("Functions saved to: {0}", functionsOutputFile);

                SaveErrors(allErrors, errorsOutputFile);
                Console.WriteLine("Errors saved to: {0}\n", errorsOutputFile);

                
                PrintSummary(tokens.Count, visitor.GetGlobalVariables().Count, visitor.GetFunctions().Count, allErrors.Count);
            }
            catch (Exception ex)
            {
                Console.WriteLine("EXCEPTION: {0}", ex.Message);
                Console.WriteLine("Stack trace: {0}", ex.StackTrace);
                File.WriteAllText(errorsOutputFile, "EXCEPTION: " + ex.Message + "\n" + ex.StackTrace + "\n");
            }

            Console.WriteLine("\nPress Enter to exit...");
            Console.ReadLine();
        }

        static void SaveTokens(ArrayList tokens, string filename)
        {
            using (StreamWriter writer = new StreamWriter(filename))
            {
                writer.WriteLine("=== LEXICAL TOKENS ===");
                writer.WriteLine("Generated by LFC Compiler\n");
                writer.WriteLine("Format: <TOKEN_TYPE, LEXEME, LINE_NUMBER>\n");
                
                int count = 0;
                for (int i = 0; i < tokens.Count; i++)
                {
                    writer.WriteLine(tokens[i].ToString());
                    count++;
                }
                
                writer.WriteLine("\n=====================================");
                writer.WriteLine("Total tokens: {0}", count);
                writer.WriteLine("=====================================");
            }
        }

        static void SaveGlobalVariables(ArrayList variables, string filename)
        {
            using (StreamWriter writer = new StreamWriter(filename))
            {
                writer.WriteLine("=== GLOBAL VARIABLES ===");
                writer.WriteLine("Generated by LFC Compiler\n");
                
                if (variables.Count == 0)
                {
                    writer.WriteLine("No global variables declared in this program.\n");
                }
                else
                {
                    writer.WriteLine("List of all global variables:\n");
                    for (int i = 0; i < variables.Count; i++)
                    {
                        writer.WriteLine("{0}. {1}", (i + 1), variables[i].ToString());
                    }
                    writer.WriteLine("\n=====================================");
                    writer.WriteLine("Total global variables: {0}", variables.Count);
                    writer.WriteLine("=====================================");
                }
            }
        }

        static void SaveFunctions(ArrayList functions, string filename)
        {
            using (StreamWriter writer = new StreamWriter(filename))
            {
                writer.WriteLine("=== FUNCTIONS ===");
                writer.WriteLine("Generated by LFC Compiler\n");
                
                if (functions.Count == 0)
                {
                    writer.WriteLine("No functions declared in this program.\n");
                }
                else
                {
                    writer.WriteLine("List of all functions:\n");
                    for (int i = 0; i < functions.Count; i++)
                    {
                        writer.WriteLine("{0}. {1}", (i + 1), functions[i].ToString());
                    }
                    writer.WriteLine("\n=====================================");
                    writer.WriteLine("Total functions: {0}", functions.Count);
                    writer.WriteLine("=====================================");
                }
            }
        }

        static void SaveErrors(ArrayList errors, string filename)
        {
            using (StreamWriter writer = new StreamWriter(filename))
            {
                writer.WriteLine("=== COMPILATION ERRORS/WARNINGS ===");
                writer.WriteLine("Generated by LFC Compiler\n");
                
                if (errors.Count == 0)
                {
                    writer.WriteLine("No errors detected during compilation.\n");
                    writer.WriteLine("The source code passed all validation checks:");
                    writer.WriteLine("  - Lexical validation: PASS");
                    writer.WriteLine("  - Syntactic validation: PASS");
                    writer.WriteLine("  - Semantic validation: PASS");
                }
                else
                {
                    writer.WriteLine("{0} error(s) detected during compilation:\n", errors.Count);
                    for (int i = 0; i < errors.Count; i++)
                    {
                        writer.WriteLine("{0}. {1}", (i + 1), errors[i].ToString());
                    }
                    writer.WriteLine("\n=====================================");
                    writer.WriteLine("Total errors: {0}", errors.Count);
                    writer.WriteLine("=====================================");
                }
            }
        }

        static void PrintSummary(int tokenCount, int varCount, int funcCount, int errorCount)
        {
            Console.WriteLine("====================================");
            Console.WriteLine("   COMPILATION SUMMARY REPORT");
            Console.WriteLine("====================================");
            Console.WriteLine("Tokens Identified:      {0}", tokenCount);
            Console.WriteLine("Global Variables:       {0}", varCount);
            Console.WriteLine("Functions Defined:      {0}", funcCount);
            Console.WriteLine("Total Errors:           {0}", errorCount);
            Console.WriteLine("====================================");

            if (errorCount == 0)
            {
                Console.WriteLine("Status: SUCCESS");
            }
            else
            {
                Console.WriteLine("Status: FAILED ({0} error(s))", errorCount);
            }

            Console.WriteLine("====================================");
        }
    }
}
